name: Continuous Integration

on:
  push:
    branches: [ master ]

jobs:

  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run:  sudo apt-get update && sudo apt-get install libtiff-dev libpng-dev libturbojpeg-dev libwebp-dev libmemcached-dev libopenjp2-7-dev

    - name: Configure
      run: |
        ./autogen.sh
        ./configure

    - name: Compile
      run: make


  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install automake fcgi libtiff openjpeg libmemcached libpng webp

    - name: Configure
      run: |
        ./autogen.sh
        ./configure

    - name: Compile
      run: make
